import { Metadata } from "next";
import CodeBlock from "@/components/docs/code-block";

export const metadata: Metadata = {
  title: "Bolt.new Integration - LLM.kiwi API",
  description: "Build full-stack applications with Bolt.new using LLM.kiwi.",
};

export default function BoltNewPage() {
  return (
    <div className="space-y-10">
      <div>
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-4">
          Bolt.new Integration
        </h1>
        <p className="text-gray-600 dark:text-gray-400 text-lg">
          Bolt.new is an AI web development agent that builds, runs, and deploys
          full-stack apps in the browser.
        </p>
      </div>

      <section>
        <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
          Using LLM.kiwi in Bolt Apps
        </h2>
        <p className="text-gray-600 dark:text-gray-400 mb-4">
          When Bolt generates an application for you, instruct it to use
          LLM.kiwi as the backend for any AI features.
        </p>

        <div className="bg-purple-50 dark:bg-purple-900/20 p-4 rounded-lg border border-purple-200 dark:border-purple-800 mb-6">
          <h3 className="font-medium text-purple-900 dark:text-purple-100 mb-2">
            Prompt Example
          </h3>
          <p className="text-purple-800 dark:text-purple-200 italic">
            &quot;Build a chat application. Use the OpenAI SDK but configure it
            to point to &apos;https://api.llm.kiwi/v1&apos; as the base URL. Use
            an environment variable &apos;LLM_API_KEY&apos; for
            authentication.&quot;
          </p>
        </div>

        <h3 className="font-medium text-gray-900 dark:text-white mt-6 mb-3">
          Manual Configuration
        </h3>
        <p className="text-gray-600 dark:text-gray-400 mb-3">
          If you are editing the code generated by Bolt:
        </p>
        <CodeBlock
          examples={[
            {
              language: "typescript",
              label: "lib/ai.ts",
              code: `import OpenAI from 'openai';

export const openai = new OpenAI({
  apiKey: process.env.LLM_API_KEY,
  baseURL: 'https://api.llm.kiwi/v1',
  dangerouslyAllowBrowser: true // Only if calling from client-side (not recommended)
});`,
            },
          ]}
        />
      </section>
    </div>
  );
}
